name: pycrown
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy>=1.23
  - scipy>=1.9
  - scikit-image>=0.20
  - rasterio>=1.3
  - numba>=0.60
  - fiona>=1.9
  - networkx>=3.0
  - pip
  - pip:
    - pycrown-simplified
